FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar telemedicine-service.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "telemedicine-service.jar"]
