server.port=${SERVER_PORT:8082}
spring.application.name=patient-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/patient_service_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${APP_JWT_SECRET:mySecretKeyForJwtTokenGenerationAndValidationPurposesOnly123456789}
services.appointment.base-url=${APPOINTMENT_SERVICE_BASE_URL:http://localhost:8085/api/appointments}
services.prescription.base-url=${PRESCRIPTION_SERVICE_BASE_URL:http://localhost:8083/api/prescriptions}

# AWS S3 Configuration
aws.region=${AWS_REGION:eu-north-1}
aws.s3.bucket=${AWS_S3_BUCKET:patient-reports-damith-001}
aws.credentials.access-key=${AWS_ACCESS_KEY_ID:AKIAXPP4E6ECQL6Z5AE5}
aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY: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}

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Error Response Configuration
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
