# Server
server.port=8082
spring.application.name=patient-service

# Neon Database
spring.datasource.url=jdbc:postgresql://ep-winter-glitter-amoy4758-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EfRw25jdsQIi
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SSL (IMPORTANT for Neon)
spring.datasource.hikari.ssl=true
spring.datasource.hikari.sslmode=require

# JWT
app.jwt.secret=mySecretKeyForJwtTokenGenerationAndValidationPurposesOnly123456789

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always