spring.application.name=auth-service

# ====================== PostgreSQL Configuration ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=your-super-secret-key-at-least-256-bits-long-use-a-strong-random-one
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# Server Configuration
server.port=8081

# Flyway
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=true

# Swagger Documentation (OpenAPI 3)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.se73.auth_service