distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.0/apache-maven-3.9.0-bin.zip
distributionSha256Sum=d06ed1f1e89a1e5a0a5f1b475e4aa9374e48b962e1a8a00d41b9e77f04a85e5f
wrapperVersion=3.3.4
