CREATE TABLE patient_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    address VARCHAR(255),
    date_of_birth DATE
);

CREATE TABLE medical_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    minio_path VARCHAR(255) NOT NULL,
    file_type VARCHAR(255),
    file_size BIGINT,
    description VARCHAR(255),
    uploaded_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_medical_reports_patient
        FOREIGN KEY (patient_id) REFERENCES patient_profiles (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_medical_reports_patient_id ON medical_reports(patient_id);