apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  labels:
    app: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
      - name: doctor-service
        image: doctor-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: doctor-config
              key: SERVER_PORT
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://doctor-db-service:5432/doctor_service_db
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: doctor-config
              key: DB_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: doctor-secret
              key: DB_PASSWORD
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 40
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
