apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-db
  labels:
    app: appointment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-db
  template:
    metadata:
      labels:
        app: appointment-db
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: appointment-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: appointment-config
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appointment-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: appointment-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: appointment-db-storage
        emptyDir: {}
