apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: default
data:
  AUTH_SERVICE_BASE_URL: http://auth-service:8081/api/auth
  PATIENT_SERVICE_BASE_URL: http://patient-service:8082/api/patients
  DOCTOR_SERVICE_BASE_URL: http://doctor-service:8083/api/doctors
  SYMPTOM_CHECKER_SERVICE_BASE_URL: http://ai-symptom-checker:8087/api/symptoms
  APPOINTMENT_SERVICE_BASE_URL: http://appointment-service:8085/api/appointments
  TELEMEDICINE_SERVICE_BASE_URL: http://telemedicine-service:8084/api/telemedicine
  PAYMENT_SERVICE_BASE_URL: http://payment-service:8086/api/payments
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: default
type: Opaque
data:
  # Values are base64 encoded
  APP_JWT_SECRET: bXlTZWNyZXRLZXlGb3JKd3RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uUHVycG9zZXNPbmx5MTIzNDU2Nzg5
