apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-config
  namespace: default
data:
  DB_HOST: shared-postgres-service
  DB_PORT: "5432"
  DB_NAME: patient_service_db
  DB_USERNAME: postgres
  SERVER_PORT: "8082"
  APPOINTMENT_SERVICE_BASE_URL: http://appointment-service:8085/api/appointments
  PRESCRIPTION_SERVICE_BASE_URL: http://doctor-service:8083/api/prescriptions
  AWS_REGION: eu-north-1
  AWS_S3_BUCKET: patient-reports-damith-001
---
apiVersion: v1
kind: Secret
metadata:
  name: patient-secret
  namespace: default
type: Opaque
stringData:
  # Values are base64 encoded
  DB_PASSWORD: cG9zdGdyZXM= # postgres
  APP_JWT_SECRET: bXlTZWNyZXRLZXlGb3JKd3RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uUHVycG9zZXNPbmx5MTIzNDU2Nzg5
  AWS_ACCESS_KEY_ID: AKIAXPP4E6ECQL6Z5AE5 # base64 encoded
  AWS_SECRET_ACCESS_KEY: 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
