apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: default
data:
  DB_HOST: shared-postgres-service
  DB_PORT: "5432"
  DB_NAME: notification_service_db
  DB_USERNAME: postgres
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
  MAIL_FROM: no-reply@ds-project.local
  PATIENT_SERVICE_URL: http://patient-service:8082/api/patients
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: default
type: Opaque
stringData:
  # Values are base64 encoded
  DB_PASSWORD: cG9zdGdyZXM= # postgres
  JWT_SECRET: bXlTZWNyZXRLZXlGb3JKd3RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uUHVycG9zZXNPbmx5MTIzNDU2Nzg5
  MAIL_USERNAME: "uthsarapavan@gmail.com" 
  MAIL_PASSWORD: "sezvvihsyzvzeafw"
